### ISSUE TITLE
wrong kind of value returned from append_to_stream

### ISSUE THREAD

**Issue by norpan** [commanded/commanded-extreme-adapter#23]
I get the following error. It seems that `append_to_stream` returns an error triple, but only error tuples are allowed.
```
** (WithClauseError) no with clause matching: {:error, :CommitTimeout, %Extreme.Msg.WriteEventsCompleted{commit_position: 0, first_event_number: -2147483648, last_event_number: -2147483648, message: "Commit phase timeout.", prepare_position: -2147483648, result: :CommitTimeout}}
    (commanded) lib/commanded/aggregates/aggregate.ex:458: Commanded.Aggregates.Aggregate.persist_events/4
    (commanded) lib/commanded/aggregates/aggregate.ex:433: Commanded.Aggregates.Aggregate.execute_command/2
    (commanded) lib/commanded/aggregates/aggregate.ex:192: Commanded.Aggregates.Aggregate.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by dvxam** [comment]
I've got the same issue here, no sure how it should be solved
